name: Deploy to AKS from ACR

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: test0107.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build Docker image
      run: |
        docker build -t test0107.azurecr.io/asg:${{ github.sha }} .
        docker push test0107.azurecr.io/asg:${{ github.sha }}
    - name: Pull Docker image from ACR
      run: |
        docker pull test0107.azurecr.io/asg:${{ github.sha }}
    - name: Create Secret
      run: |
        kubectl create secret docker-registry acr-secret --docker-server= test0107.azurecr.io --docker-username= bbbc71f9-f13a-4e01-a366-e4ef5270c9fe --docker-password= pPU8Q~w7sbZI9w11g_7UAAX8vLx90tsJS58dOaqt --docker-email=naveennadendla479@gmail.com

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group test --name project --overwrite-existing
        kubectl apply -f deployment.yaml
    
   # - name: Set up kubectl
    #  uses: azure/k8s-set-context@v1
   #   with:
    #    kubeconfig: ${{ secrets.KUBE_CONFIG }}
    #    version: 'v1.21.0'  # Adjust Kubernetes version as needed
    
  #  - name: Deploy to AKS
   #   run: |
  #      kubectl apply -f deployment.yaml
    
#    - name: Build Docker image
 #     run: |
  #      docker build -t ${{ secrets.ACR_LOGIN_SERVER }}test0107.azurecr.io/asg:${{ github.sha }} .
  #      docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
  #      docker push ${{ secrets.ACR_LOGIN_SERVER }}test0107.azurecr.io/asg:${{ github.sha }}
    
  #  - name: Pull Docker image from ACR
   #   run: |
  #      az acr login --name <acr-name>
   #     docker pull ${{ secrets.ACR_LOGIN_SERVER }}test0107.azurecr.io/asg:${{ github.sha }}
    
 #   - name: Set up kubectl
  #    uses: azure/k8s-set-context@v1
  #    with:
  #      kubeconfig: ${{ secrets.KUBE_CONFIG }}
  #      version: 'v1.21.0'  # Adjust Kubernetes version as needed
    
  #  - name: Deploy to AKS
   #   run: |
     #   kubectl apply -f path/to/your/kubernetes/manifests
